spring:
  application:
    name: user-service

  # Vault Configuration
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:false}
      uri: ${VAULT_URI:http://localhost:8200}
      token: ${VAULT_TOKEN}
      scheme: http
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:mydatabase}
    username: ${db.user:myuser}
    password: ${db.password:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
