services:
  frontend-service:
    build: ./frontend/travel-orch
    container_name: frontend-service
    ports:
      - "4200:2122"
    depends_on:
      - apigateway-service
    networks:
      - microservices-network

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    networks:
      - microservices-network

  travel-service:
    build: ./backend/travel-service
    container_name: travel-service
    networks:
      - microservices-network

  user-service:
    build: ./backend/user-service
    container_name: user-service
    networks:
      - microservices-network

  apigateway-service:
    build: ./backend/apigateway-service
    container_name: apigateway-service
    ports:
      - "8443:8443"
    depends_on:
      - user-service
      - travel-service
      - payment-service
    networks:
      - microservices-network
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservices-network:
    driver: bridge
