spring.application.name=apigateway-service

server.port=8443

server.ssl.key-store=classpath:spring-dev.p12
server.ssl.key-store-password=esouq123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=esouq
server.ssl.enabled=true
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowed-origins[0]=https://*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowed-methods=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

